server:
  port: 8081
spring:
  application:
    name: tasks-tracker
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tasks
    username: postgres
    password: admin
  jpa:
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: CLIENT_ID
            client-secret: CLIENT_SECRET
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs
    url: /openapi.yaml
  # show-actuator: true


logging:
  level:
    root: info